### ISSUE TITLE
contact-us.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [KaplinSergey/AngularMentoring#12]
`{ provide: ConstantsService, useValue: { App: 'TaskManager', Ver: '1.0'} },`
`@Inject(ConstantsService) private constant: string,`

Если ConstantsService класс, то можно не использовать @Inject, Значение, связанное с этим токеном - это объект, хотя у вас объявлено, что constant: string

**Comment by KaplinSergey** [comment]
fixed
