### ISSUE TITLE
WARNING in Circular dependency detected:

### ISSUE THREAD

**Issue by VZhyrytskiy** [KaplinSergey/AngularMentoring#19]
Во время компиляции возникает предупреждение
```
WARNING in Circular dependency detected:
[0] src\app\core\services\constants\constants.service.ts -> src\app\core\core.module.ts -> src\app\core\components\contact-us\contact-us.component.ts -> src\app\core\services\constants\constants.service.ts
```

Оно появляется из-за того, что при регистрации сервиса используется
`providedIn: CoreModule`
а затем в этом модуле
`declarations: [ContactUsComponent, ChangeHostElementDirective, TextClickDirective],`
задекларирован компонент, который использует этот сервис.
Решений несколько:
1. использовать `providedIn: 'root'`
2. создать отдельный модуль, который испольовать только для регисрации сервисов так, чтобы в нем не было массива declarations

**Comment by KaplinSergey** [comment]
fixed in Task 7
